const fs=require('fs'),convert=require('xml-js'),protobuf=require('protobufjs');
const root=protobuf.loadSync('employee.proto'),EmpType=root.lookupType('Employees');
const empList=[{id:1,name:'Ali',salary:9000},{id:2,name:'Kamal',salary:22000},{id:3,name:'Amal',salary:23000}];
const payload={employee:empList};
console.time('JSON encode');
const jsonStr=JSON.stringify(payload);
console.timeEnd('JSON encode');
console.time('JSON decode');
JSON.parse(jsonStr);
console.timeEnd('JSON decode');
const xmlOpts={compact:true,ignoreComment:true,spaces:0};
console.time('XML encode');
const xmlStr="<root>\n"+convert.json2xml(payload,xmlOpts)+"\n</root>";
console.timeEnd('XML encode');
console.time('XML decode');
JSON.parse(convert.xml2json(xmlStr,{compact:true}));
console.timeEnd('XML decode');
const err=EmpType.verify(payload);
if(err)throw Error(err);
console.time('Protobuf encode');
const pBuf=EmpType.encode(EmpType.create(payload)).finish();
console.timeEnd('Protobuf encode');
console.time('Protobuf decode');
EmpType.toObject(EmpType.decode(pBuf));
console.timeEnd('Protobuf decode');
fs.writeFileSync('data.json',jsonStr);fs.writeFileSync('data.xml',xmlStr);fs.writeFileSync('data.proto',pBuf);
console.log(`Taille JSON : ${fs.statSync('data.json').size} octets`);
console.log(`Taille XML  : ${fs.statSync('data.xml').size} octets`);
console.log(`Taille Protobuf: ${fs.statSync('data.proto').size} octets`);